Here's trying to figure out what's going on in #15.

FIrst off, permutation matrices.

## Permutation Matrices

We want to make a matrix $P$ such that $AP$ shuffles around the *columns* of $A$.  Let's make a sample matrix $A$ in which the columns are all of the same number.

In [1]:
import numpy as np
A = np.zeros((5,5 ))
for i in range(5):
  A[:, i]  = i + 1
print('A=')
print(A)

A=
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


Now let's figure out $P$.  If we imagine performing the matrix mulitplication $AP$ we first take the first *row* of $A$, and dot it together with each *column* of $P$. The resulting 5 numbers are the first *row* of $AP$. 

If you stare at this long enough, you'll see that $P[0, 3]=1$ will mean to insert the `0`th column of $A$ into the `3`rd column of $AP$:

In [2]:
P = np.zeros((5, 5))
P[0, 3] = 1

print('P=')
print(P)
print()
print('AP=')
print(A @ P)

P=
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

AP=
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]


Let's do this again, but reversing all of the columns:

In [3]:
P = np.zeros((5, 5))
P[0, 4] = P[4, 0] = 1
P[1, 3] = P[3, 1] = 1
P[2, 2] = 1
print('P=')
print(P)
print()
print('AP=')
print(A @ P)

P=
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]

AP=
[[5. 4. 3. 2. 1.]
 [5. 4. 3. 2. 1.]
 [5. 4. 3. 2. 1.]
 [5. 4. 3. 2. 1.]
 [5. 4. 3. 2. 1.]]


### Swapping Rows
Okay, what about swapping rows? Let's first make another test matrix $B$ so that we can look at the rows:

In [4]:
B = np.zeros((5,5 ))
for i in range(5):
  B[i, :]  = i + 1
print('B=')
print(B)

B=
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]


Now the magic is that $P$ still works to shuffle aorund the things, but we have to multiply it from the other side. $PB$ is $B$ but with all *rows* shuffled.

In [5]:
print("PB=")
print(P@B)

PB=
[[5. 5. 5. 5. 5.]
 [4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]]


We can also make another a little more interesting matrix $C$ with all different numbers in it. 

In [6]:
C = np.array([i for i in range(25)]).reshape((5, 5))
print('C=')
print(C)

C=
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Then we can multiply $P$ on both sides of $C$ to see what happens:

In [7]:
print("PCP=")
print(P @ C @ P)

PCP=
[[24. 23. 22. 21. 20.]
 [19. 18. 17. 16. 15.]
 [14. 13. 12. 11. 10.]
 [ 9.  8.  7.  6.  5.]
 [ 4.  3.  2.  1.  0.]]


We get both reversed rows and columns!

## Composing
Lastly, let's see what these things look like when we compose them.
We'll reuse $Q$ from above, but we'll make two new transposition matrices, one that swaps $[2,3]$ and one that swaps [$1,2]$.

In [8]:
swap_23 = np.zeros((5, 5))
swap_23[0, 0] = 1
swap_23[1, 1] = 1
swap_23[3, 2] = swap_23[2, 3] = 1
swap_23[4, 4] = 1
print('swap_23=')
print(swap_23)
print()

swap_12 = np.zeros((5, 5))
swap_12[0, 0] = 1
swap_12[1, 2] = swap_12[2, 1] = 1
swap_12[3, 3] = 1
swap_12[4, 4] = 1
print('swap_12=')
print(swap_12)

swap_23=
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]

swap_12=
[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Let's first check that the order matters:

In [9]:
print('swap_12 * swap_23=')
print(swap_12 @ swap_23)
print()
print('swap_23 * swap_12=')
print(swap_23 @ swap_12)

swap_12 * swap_23=
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]

swap_23 * swap_12=
[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


The matrices are different, which makes sense, since swapping (2,3) and then (1,2) is different than swapping (1,2) and then (2,3).

Furthermore, we can better understand if we were to use this, by looking at the matrix multiplication:

$$ A (S_{12} S_{23}) = (A S_{12}) S_{23} $$

I.e, if we mulitply $A$ by the composition of $S_{12}$ and $S_{23}$, we get the same result as if we first multiply $A$ by $S_{12}$ and then multiply the result by $S_{23}$.  This is multiplication from the *right*, so we are swapping *columns*.  The result is that we first swap column 1 and 2, and then swap column 2 and 3.

In [10]:
print('A=')
print(A)
print()
print('A swap_12=')
print(A @ swap_12)
print()
print('A swap_12 swap_23=')
print(A @ swap_12 @ swap_23)

A=
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]

A swap_12=
[[1. 3. 2. 4. 5.]
 [1. 3. 2. 4. 5.]
 [1. 3. 2. 4. 5.]
 [1. 3. 2. 4. 5.]
 [1. 3. 2. 4. 5.]]

A swap_12 swap_23=
[[1. 3. 4. 2. 5.]
 [1. 3. 4. 2. 5.]
 [1. 3. 4. 2. 5.]
 [1. 3. 4. 2. 5.]
 [1. 3. 4. 2. 5.]]
